disabled_rules:
  - function_parameter_count

included:
  - Sources
  - Tests
  - Package.swift

trailing_comma:
  mandatory_comma: true

line_length:
  warning: 240
  error: 260
  ignores_comments: true

type_body_length:
  - 400
  - 500

identifier_name:
  allowed_symbols: "_"
  excluded:
    - at
