name: CI

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  swiftpm:
    name: SwiftPM on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest']
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - name: Show xcodebuild version
        run: xcodebuild -version
      - name: Show Swift version
        run: swift --version
      - name: Build Swift package
        run: swift build -v -c release
      - name: Test Swift package
        run: swift test -v -Xswiftc -warnings-as-errors

  codecov:
    name: codecov on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest']
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - name: export-codecov
        run: make export-codecov
      - name: codecov
        if: success()
        uses: codecov/codecov-action@v7
        with:
          files: coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}

  xcode:
    name: ${{ matrix.make-target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest']
        make-target:
          [
            xcode-test,
            pod-lib-lint,
            bazel-test,
          ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - run: make ${{ matrix.make-target }}
